#!/usr/bin/escript
%%! -pz /home/donpiekarz/dev/erlang/FatFish/fatfish/deps/gen_smtp/ebin/

main([]) ->
    application:start(asn1),
    application:start(crypto),
    application:start(public_key),
    application:start(ssl),
    %io:fwrite("liby: ~p~n", [code:get_path()]),
    From = "koparka.zolta@gmail.com",
    To =  ["m8r-bcjpr@mailinator.com"],
    Data = "Subject: testing\r\nFrom: Andrew Thompson \r\nTo: Some Dude <czerwona.koparka@mailinator.com> \r\n\r\nThis is the email body",
    Options = [
               {relay, "smtp.gmail.com"},
%               {relay, "gmail.com"},
               %{relay, "smtp.googlemail.com"},
               {username, "koparka.zolta@gmail.com"},
               {password, "kopareczko"},
               {auth, always},
               {tls, always}
               %{ssl, true}
               %{port, 465}
              ],

    Res = gen_smtp_client:send_blocking({From, To, Data}, Options),
    io:fwrite("wyjscie: ~p~n", [Res]).
