%% Generated by the Erlang ASN.1 compiler version:3.0.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module AttributeCertificateVersion1



-ifndef(_ATTRIBUTECERTIFICATEVERSION1_HRL_).
-define(_ATTRIBUTECERTIFICATEVERSION1_HRL_, true).

-record('AttributeCertificateV1',{
acInfo, signatureAlgorithm, signature}).

-record('AttributeCertificateInfoV1',{
version = asn1_DEFAULT, subject, issuer, signature, serialNumber, attCertValidityPeriod, attributes, issuerUniqueID = asn1_NOVALUE, extensions = asn1_NOVALUE}).

-endif. %% _ATTRIBUTECERTIFICATEVERSION1_HRL_
